### ISSUE TITLE
Firefox.xpi

### ISSUE THREAD

**Issue by JalfResi** [fedesog/webdriver#3]
How do I extract the firefox.xpi out of the selenium-server-standalone.jar file in order to use the FireFox driver? Also, what is the significance of the first argument of the NewFireFoxDriver() function?

**Comment by fedesog** [comment]
jar should be able to extract a jar file, I just use unzip from terminal (on Linux)
$ unzip -d selenium selenium-server-standalone-version.jar
$ find selenium -name webdriver.xpi
selenium/org/openqa/selenium/firefox/webdriver.xpi

the first argument is the path to firefox executable, just "firefox" is probably fine since it should be in PATH

**Comment by JalfResi** [comment]
Perfect! That worked first time under OSX. Thanks!

P.S Love this package, so useful!
